import { Modal, Notice, Setting } from 'obsidian';
import type BabylonPlugin from '../../main';
import { tr } from '../../i18n';
import type { MediaType, SupportedLocale } from '../../types';
import { getFields } from '../../fields/FieldRegistry';
import { addFolderPicker } from './FolderPicker';

export class GenerateTemplateModal extends Modal {
	private plugin: BabylonPlugin;
	private mediaType: MediaType;
	private fileName: string;
	private folder: string;
	private language: SupportedLocale;

	constructor(plugin: BabylonPlugin, mediaType: MediaType) {
		super(plugin.app);
		this.plugin = plugin;
		this.mediaType = mediaType;
		this.fileName = `${mediaType}-template.md`;
		this.folder = plugin.settings.templateFolder || 'Templates';
		this.language = plugin.settings.language;
	}

	onOpen(): void {
		const { contentEl } = this;
		contentEl.createEl('h2', { text: tr('gen-template-title') });

		new Setting(contentEl)
			.setName(tr('gen-template-filename'))
			.addText((text) => {
				text.setValue(this.fileName);
				text.onChange((v) => { this.fileName = v.trim(); });
			});

		const folderSetting = new Setting(contentEl)
			.setName(tr('gen-template-folder'));

		addFolderPicker(
			folderSetting,
			this.app,
			this.folder,
			(v) => { this.folder = v; },
		);

		new Setting(contentEl)
			.setName(tr('gen-template-language'))
			.addDropdown((dropdown) => {
				dropdown.addOption('en', 'English');
				dropdown.addOption('ru', 'Русский');
				dropdown.setValue(this.language);
				dropdown.onChange((v) => { this.language = v as SupportedLocale; });
			});

		new Setting(contentEl).addButton((btn) => {
			btn.setButtonText(tr('cancel'));
			btn.onClick(() => this.close());
		}).addButton((btn) => {
			btn.setButtonText(tr('gen-template-generate'));
			btn.setCta();
			btn.onClick(() => this.generate());
		});
	}

	private async generate(): Promise<void> {
		const settings = this.plugin.settings.media[this.mediaType];
		if (!settings) return;

		const allFields = getFields(this.mediaType);
		const selectedFieldKeys = settings.selectedFields ?? [];
		const customFieldKeys = settings.customFieldNames ?? [];

		const header = this.language === 'en'
			? [
				'# auto-generated by Babylon',
				'# Edit this file to customize your notes.',
			]
			: [
				'# авто-сгенерировано Babylon',
				'# Отредактируйте этот файл, чтобы настроить формат заметок.',
			];

		const frontmatterLines = [...header];
		for (const key of selectedFieldKeys) {
			const def = allFields.find((f) => f.key === key);
			const placeholder = def?.key ?? key;
			frontmatterLines.push(`${key}: {{${placeholder}}}`);
		}
		for (const key of customFieldKeys) {
			frontmatterLines.push(`${key}: {{${key}}}`);
		}

		const bodyLines: string[] = [];
		const isEn = this.language === 'en';

		// template summary
		const fieldNames = [...selectedFieldKeys, ...customFieldKeys];
		const fieldsHelp = fieldNames.join(', ');

		if (isEn) {
			bodyLines.push(
				'',
				'---',
				'',
				'## Template usage',
				'',
				`Placeholders like \`{{title}}\` are replaced with data when creating notes.`,
				`Reorder, add or remove fields in the frontmatter above as you like.`,
				`Available placeholders: ${fieldsHelp}`,
				`Unknown placeholders remain as-is \u2014 use them for custom data.`,
				`Set this template in **Settings \u2192 ${this.mediaType} \u2192 Template file**.`,
				'',
			);
		} else {
			bodyLines.push(
				'',
				'---',
				'',
				'## Использование шаблона',
				'',
				`Плейсхолдеры вида \`{{title}}\` заменяются данными при создании заметок.`,
				`Вы можете менять порядок, добавлять и удалять поля в frontmatter выше.`,
				`Доступные плейсхолдеры: ${fieldsHelp}`,
				`Неизвестные плейсхолдеры остаются как есть \u2014 используйте для своих данных.`,
				`Укажите этот шаблон в **Настройки \u2192 ${this.mediaType} \u2192 Файл шаблона**.`,
				'',
			);
		}

		const content = [
			'---',
			...frontmatterLines,
			'---',
			...bodyLines,
		].join('\n');

		const filePath = this.folder
			? `${this.folder.replace(/^\/+|\/+$/g, '')}/${this.fileName}`
			: this.fileName;

		try {
			await this.ensureFolder(this.folder);
			await this.app.vault.create(filePath, content);
			settings.templatePath = filePath;
			await this.plugin.saveSettings();
			new Notice(tr('gen-template-success', { path: filePath }));
			this.close();
			this.plugin.settingsTab?.display();
		} catch (err) {
			console.error('Babylon: Template creation failed', err);
			new Notice(tr('gen-template-error'));
		}
	}

	private async ensureFolder(folder: string): Promise<void> {
		if (!folder) return;
		const parts = folder.split('/');
		let current = '';
		for (const part of parts) {
			current = current ? `${current}/${part}` : part;
			if (!current) continue;
			const exists = this.app.vault.getAbstractFileByPath(current);
			if (!exists) {
				try {
					await this.app.vault.createFolder(current);
				} catch {
					// ignore
				}
			}
		}
	}

	onClose(): void {
		this.contentEl.empty();
	}
}
