import { Modal, Notice, Setting, TFile } from 'obsidian';
import type BabylonPlugin from '../../main';
import { tr } from '../../i18n';
import type { MediaType, SupportedLocale } from '../../types';
import { getFields } from '../../fields/FieldRegistry';
import { addFolderPicker } from './FolderPicker';
import { ConfirmModal } from '../../ui/modals/ConfirmModal';

export class GenerateTemplateModal extends Modal {
	private plugin: BabylonPlugin;
	private mediaType: MediaType;
	private fileName: string;
	private folder: string;
	private language: SupportedLocale;

	constructor(plugin: BabylonPlugin, mediaType: MediaType) {
		super(plugin.app);
		this.plugin = plugin;
		this.mediaType = mediaType;
		this.fileName = `${mediaType}-template.md`;
		this.folder = plugin.settings.templateFolder || 'Templates';
		this.language = plugin.settings.language;
	}

	onOpen(): void {
		const { contentEl } = this;
		contentEl.createEl('h2', { text: tr('gen-template-title') });

		new Setting(contentEl)
			.setName(tr('gen-template-filename'))
			.addText((text) => {
				text.setValue(this.fileName);
				text.onChange((v) => { this.fileName = v.trim(); });
			});

		const folderSetting = new Setting(contentEl)
			.setName(tr('gen-template-folder'));

		addFolderPicker(
			folderSetting,
			this.app,
			this.folder,
			(v) => { this.folder = v; },
		);

		new Setting(contentEl)
			.setName(tr('gen-template-language'))
			.addDropdown((dropdown) => {
				dropdown.addOption('en', 'English');
				dropdown.addOption('ru', 'Русский');
				dropdown.setValue(this.language);
				dropdown.onChange((v) => { this.language = v as SupportedLocale; });
			});

		new Setting(contentEl).addButton((btn) => {
			btn.setButtonText(tr('cancel'));
			btn.onClick(() => this.close());
		}).addButton((btn) => {
			btn.setButtonText(tr('gen-template-generate'));
			btn.setCta();
			btn.onClick(() => this.generate());
		});
	}

	private async generate(): Promise<void> {
		const settings = this.plugin.settings.media[this.mediaType];
		if (!settings) return;

		const content = this.buildTemplateContent(settings);
		const filePath = this.folder
			? `${this.folder.replace(/^\/+|\/+$/g, '')}/${this.fileName}`
			: this.fileName;

		const existing = this.app.vault.getAbstractFileByPath(filePath);
		if (existing) {
			new ConfirmModal(
				this.app,
				tr('file-exists'),
				filePath,
				() => void this.writeTemplate(filePath, content),
			).open();
		} else {
			await this.writeTemplate(filePath, content);
		}
	}

	private buildTemplateContent(settings: { selectedFields?: string[]; customFieldNames?: string[] }): string {
		const allFields = getFields(this.mediaType);
		const knownKeys = new Set(allFields.map((f) => f.key));
		const customFieldKeys = settings.customFieldNames ?? [];

		const fieldOrder = new Map(allFields.map((f, i) => [f.key, i]));
		const selectedFieldKeys = (settings.selectedFields ?? [])
			.filter((f) => knownKeys.has(f) || customFieldKeys.includes(f))
			.sort((a, b) => {
				const oa = fieldOrder.get(a);
				const ob = fieldOrder.get(b);
				if (oa !== undefined && ob !== undefined) return oa - ob;
				if (oa !== undefined) return -1;
				if (ob !== undefined) return 1;
				return 0;
			});

		const header = this.language === 'en'
			? [
				'# auto-generated by Babylon',
				'# Edit this file to customize your notes.',
			]
			: [
				'# авто-сгенерировано Babylon',
				'# Отредактируйте этот файл, чтобы настроить формат заметок.',
			];

		// build a map of key -> type for format-aware template generation
		const typeMap = new Map(allFields.map((f) => [f.key, f.type]));
		const fieldLine = (key: string): string => {
			if (key === 'advancedScores') return '{{advancedScore_List}}';
			const type = typeMap.get(key) ?? 'string';
			if (type === 'number' || type === 'boolean') return `${key}: {{${key}}}`;
			if (type === 'array') {
				if (key === 'genres') return 'genres:\n{{genre_list}}';
				if (key === 'studios') return 'studios:\n{{studio_list}}';
				return `${key}: {{${key}}}`;
			}
			if (type === 'date') return `${key}: "{{${key}}}"`;
			return `${key}: "{{${key}}}"`;
		};

		const frontmatterLines = [...header];
		const added = new Set<string>();
		for (const key of selectedFieldKeys) {
			if (knownKeys.has(key) && !added.has(key)) {
				frontmatterLines.push(fieldLine(key));
				added.add(key);
			}
		}
		for (const key of customFieldKeys) {
			if (!added.has(key)) {
				frontmatterLines.push(`${key}: "{{${key}}}"`);
				added.add(key);
			}
		}

		const bodyLines: string[] = [];
		const isEn = this.language === 'en';
		const fieldNames = [...new Set([...selectedFieldKeys, ...customFieldKeys])];
		const fieldsHelp = fieldNames.join(', ');

		if (isEn) {
			bodyLines.push(
				'',
				'---',
				'',
				'# {{title}}',
				'',
				'> {{description}}',
				'',
				'**Year:** {{year}} | **Format:** {{format}} | **Episodes:** {{episodes}}',
				'**Score:** {{averageScore}}',
				'',
				'[View on AniList]({{siteUrl}})',
				'',
				'## Template usage',
				'',
				`Placeholders like \`{{title}}\` are replaced with data when creating notes.`,
				`Reorder, add or remove fields in the frontmatter above as you like.`,
				`Available placeholders: ${fieldsHelp}`,
				`Unknown placeholders remain as-is \u2014 use them for custom data.`,
				`Set this template in **Settings \u2192 ${this.mediaType} \u2192 Template file**.`,
				'',
			);
		} else {
			bodyLines.push(
				'',
				'---',
				'',
				'# {{title}}',
				'',
				'> {{description}}',
				'',
				'**Год:** {{year}} | **Формат:** {{format}} | **Эпизодов:** {{episodes}}',
				'**Оценка:** {{averageScore}}',
				'',
				'[Посмотреть на AniList]({{siteUrl}})',
				'',
				'## Использование шаблона',
				'',
				`Плейсхолдеры вида \`{{title}}\` заменяются данными при создании заметок.`,
				`Вы можете менять порядок, добавлять и удалять поля в frontmatter выше.`,
				`Доступные плейсхолдеры: ${fieldsHelp}`,
				`Неизвестные плейсхолдеры остаются как есть \u2014 используйте для своих данных.`,
				`Укажите этот шаблон в **Настройки \u2192 ${this.mediaType} \u2192 Файл шаблона**.`,
				'',
			);
		}

		return [
			'---',
			...frontmatterLines,
			'---',
			...bodyLines,
		].join('\n');
	}

	private async writeTemplate(filePath: string, content: string): Promise<void> {
		const settings = this.plugin.settings.media[this.mediaType];
		if (!settings) return;

		try {
			await this.ensureFolder(this.folder);

			const existing = this.app.vault.getAbstractFileByPath(filePath);
			if (existing instanceof TFile) {
				await this.app.vault.modify(existing, content);
			} else {
				await this.app.vault.create(filePath, content);
			}

			settings.templatePath = filePath;
			await this.plugin.saveSettings();
			new Notice(tr('gen-template-success', { path: filePath }));
			this.close();
			this.plugin.settingsTab?.display();
		} catch (err) {
			console.error('Babylon: Template creation failed', err);
			new Notice(tr('gen-template-error'));
		}
	}

	private async ensureFolder(folder: string): Promise<void> {
		if (!folder) return;
		const parts = folder.split('/');
		let current = '';
		for (const part of parts) {
			current = current ? `${current}/${part}` : part;
			if (!current) continue;
			const exists = this.app.vault.getAbstractFileByPath(current);
			if (!exists) {
				try {
					await this.app.vault.createFolder(current);
				} catch (e) {
					console.warn('Babylon: Failed to create folder', current, e);
				}
			}
		}
	}

	onClose(): void {
		this.contentEl.empty();
	}
}
