import type { FieldCategory, FieldDefinition } from '../types';

export const animeCategories: FieldCategory[] = [
	{ id: 'identity', labelKey: 'field-cat-identity', icon: 'bookmark' },
	{ id: 'info', labelKey: 'field-cat-info', icon: 'info' },
	{ id: 'ratings', labelKey: 'field-cat-ratings', icon: 'star' },
	{ id: 'technical', labelKey: 'field-cat-technical', icon: 'settings' },
	{ id: 'personal', labelKey: 'field-cat-personal', icon: 'user' },
];

const TITLE_GRAPHQL = `title { romaji english native userPreferred }`;
const COVER_GRAPHQL = `coverImage { extraLarge large medium color }`;

export const animeFields: FieldDefinition[] = [
	// ── Identity ───────────────────────────────────────────
	{
		key: 'id',
		labelKey: 'field-id',
		category: 'identity',
		type: 'number',
		personal: false,
		graphql: '',
		always: true,
	},
	{
		key: 'idMal',
		labelKey: 'field-id-mal',
		category: 'identity',
		type: 'number',
		personal: false,
		graphql: 'idMal',
		always: false,
	},
	{
		key: 'title',
		labelKey: 'field-title',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: TITLE_GRAPHQL,
		always: true,
	},
	{
		key: 'originalTitle',
		labelKey: 'field-original-title',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: '',
		always: false,
	},
	{
		key: 'title_en',
		labelKey: 'field-title-en',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: '',
		always: false,
	},
	{
		key: 'title_jp',
		labelKey: 'field-title-jp',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: '',
		always: false,
	},
	{
		key: 'title_ro',
		labelKey: 'field-title-ro',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: '',
		always: false,
	},
	{
		key: 'title_ru',
		labelKey: 'field-title-ru',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: '',
		always: false,
	},
	{
		key: 'siteUrl',
		labelKey: 'field-site-url',
		category: 'identity',
		type: 'string',
		personal: false,
		graphql: 'siteUrl',
		always: false,
	},

	// ── Info ───────────────────────────────────────────────
	{
		key: 'year',
		labelKey: 'field-year',
		category: 'info',
		type: 'number',
		personal: false,
		graphql: 'seasonYear',
		always: true,
	},
	{
		key: 'season',
		labelKey: 'field-season',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: 'season',
		always: false,
	},
	{
		key: 'seasonInt',
		labelKey: 'field-season-int',
		category: 'info',
		type: 'number',
		personal: false,
		graphql: 'seasonInt',
		always: false,
	},
	{
		key: 'startDate',
		labelKey: 'field-start-date',
		category: 'info',
		type: 'date',
		personal: false,
		graphql: 'startDate { year month day }',
		always: false,
	},
	{
		key: 'endDate',
		labelKey: 'field-end-date',
		category: 'info',
		type: 'date',
		personal: false,
		graphql: 'endDate { year month day }',
		always: false,
	},
	{
		key: 'type',
		labelKey: 'field-type',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: 'type',
		always: false,
	},
	{
		key: 'description',
		labelKey: 'field-description',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: 'description',
		always: false,
	},
	{
		key: 'cover',
		labelKey: 'field-cover',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: COVER_GRAPHQL,
		always: true,
	},
	{
		key: 'bannerImage',
		labelKey: 'field-banner',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: 'bannerImage',
		always: false,
	},
	{
		key: 'genres',
		labelKey: 'field-genres',
		category: 'info',
		type: 'array',
		format: 'list',
		personal: false,
		graphql: 'genres',
		always: true,
	},
	{
		key: 'synonyms',
		labelKey: 'field-synonyms',
		category: 'info',
		type: 'array',
		format: 'list',
		personal: false,
		graphql: 'synonyms',
		always: true,
	},
	{
		key: 'countryOfOrigin',
		labelKey: 'field-country',
		category: 'info',
		type: 'string',
		personal: false,
		graphql: 'countryOfOrigin',
		always: false,
	},

	// ── Ratings ───────────────────────────────────────────
	{
		key: 'averageScore',
		labelKey: 'field-average-score',
		category: 'ratings',
		type: 'number',
		personal: false,
		graphql: 'averageScore',
		always: true,
	},
	{
		key: 'meanScore',
		labelKey: 'field-mean-score',
		category: 'ratings',
		type: 'number',
		personal: false,
		graphql: 'meanScore',
		always: false,
	},
	{
		key: 'popularity',
		labelKey: 'field-popularity',
		category: 'ratings',
		type: 'number',
		personal: false,
		graphql: 'popularity',
		always: false,
	},
	{
		key: 'favourites',
		labelKey: 'field-favourites',
		category: 'ratings',
		type: 'number',
		personal: false,
		graphql: 'favourites',
		always: false,
	},
	{
		key: 'trending',
		labelKey: 'field-trending',
		category: 'ratings',
		type: 'number',
		personal: false,
		graphql: 'trending',
		always: false,
	},

	// ── Technical ─────────────────────────────────────────
	{
		key: 'format',
		labelKey: 'field-format',
		category: 'technical',
		type: 'string',
		personal: false,
		graphql: 'format',
		always: true,
	},
	{
		key: 'status',
		labelKey: 'field-status',
		category: 'technical',
		type: 'string',
		personal: false,
		graphql: 'status',
		always: true,
	},
	{
		key: 'episodes',
		labelKey: 'field-episodes',
		category: 'technical',
		type: 'number',
		personal: false,
		graphql: 'episodes',
		always: true,
	},
	{
		key: 'duration',
		labelKey: 'field-duration',
		category: 'technical',
		type: 'number',
		personal: false,
		graphql: 'duration',
		always: false,
	},
	{
		key: 'chapters',
		labelKey: 'field-chapters',
		category: 'technical',
		type: 'number',
		personal: false,
		graphql: 'chapters',
		always: false,
	},
	{
		key: 'volumes',
		labelKey: 'field-volumes',
		category: 'technical',
		type: 'number',
		personal: false,
		graphql: 'volumes',
		always: false,
	},
	{
		key: 'source',
		labelKey: 'field-source-material',
		category: 'technical',
		type: 'string',
		personal: false,
		graphql: 'source(version: 3)',
		always: false,
	},
	{
		key: 'hashtag',
		labelKey: 'field-hashtag',
		category: 'technical',
		type: 'string',
		personal: false,
		graphql: 'hashtag',
		always: false,
	},
	{
		key: 'updatedAt',
		labelKey: 'field-updated-at',
		category: 'technical',
		type: 'number',
		personal: false,
		graphql: 'updatedAt',
		always: false,
	},
	{
		key: 'isAdult',
		labelKey: 'field-is-adult',
		category: 'technical',
		type: 'boolean',
		format: 'checkbox',
		personal: false,
		graphql: 'isAdult',
		always: false,
	},
	{
		key: 'isLicensed',
		labelKey: 'field-is-licensed',
		category: 'technical',
		type: 'boolean',
		format: 'checkbox',
		personal: false,
		graphql: 'isLicensed',
		always: false,
	},
	{
		key: 'tags',
		labelKey: 'field-tags',
		category: 'technical',
		type: 'array',
		personal: false,
		graphql: `tags { id name description category rank isAdult }`,
		always: false,
	},
	{
		key: 'studios',
		labelKey: 'field-studios',
		category: 'technical',
		type: 'array',
		format: 'list',
		personal: false,
		graphql: `studios (isMain: true) { nodes { id name } }`,
		always: false,
	},

	// ── Advanced (hidden from UI, usable via custom fields) ─
	{
		key: 'trailer',
		labelKey: 'field-trailer',
		category: 'technical',
		type: 'string',
		advanced: true,
		personal: false,
		graphql: `trailer { id site thumbnail }`,
		always: false,
	},
	{
		key: 'streamingEpisodes',
		labelKey: 'field-streaming',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `streamingEpisodes { title url site }`,
		always: false,
	},
	{
		key: 'nextAiringEpisode',
		labelKey: 'field-next-airing',
		category: 'technical',
		type: 'object',
		advanced: true,
		personal: false,
		graphql: `nextAiringEpisode { id airingAt timeUntilAiring episode }`,
		always: false,
	},
	{
		key: 'airingSchedule',
		labelKey: 'field-airing-schedule',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `airingSchedule { edges { node { id episode airingAt } } }`,
		always: false,
	},
	{
		key: 'trends',
		labelKey: 'field-trends',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `trends { edges { node { date trending popularity episode } } }`,
		always: false,
	},
	{
		key: 'externalLinks',
		labelKey: 'field-external-links',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `externalLinks { id url site siteId type language color icon isDisabled }`,
		always: false,
	},
	{
		key: 'reviews',
		labelKey: 'field-reviews',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `reviews { edges { node { id score summary body } } }`,
		always: false,
	},
	{
		key: 'recommendations',
		labelKey: 'field-recommendations',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `recommendations { edges { node { mediaRecommendation { id title { romaji } } } } }`,
		always: false,
	},
	{
		key: 'stats',
		labelKey: 'field-stats',
		category: 'technical',
		type: 'object',
		advanced: true,
		personal: false,
		graphql: `stats { scoreDistribution { score amount } statusDistribution { status amount } }`,
		always: false,
	},
	{
		key: 'rankings',
		labelKey: 'field-rankings',
		category: 'technical',
		type: 'array',
		advanced: true,
		personal: false,
		graphql: `rankings { id rank type format year season allTime context }`,
		always: false,
	},

	// ── Personal (requires auth) ──────────────────────────
	{
		key: 'progress',
		labelKey: 'field-progress',
		category: 'personal',
		type: 'number',
		personal: true,
		graphql: 'progress',
		always: false,
	},
	{
		key: 'score',
		labelKey: 'field-score',
		category: 'personal',
		type: 'number',
		personal: true,
		graphql: 'score',
		always: false,
	},
	{
		key: 'myStatus',
		labelKey: 'field-my-status',
		category: 'personal',
		type: 'string',
		personal: true,
		graphql: 'status',
		always: false,
	},
	{
		key: 'advancedScores',
		labelKey: 'field-advanced-scores',
		category: 'personal',
		type: 'object',
		personal: true,
		graphql: 'advancedScores',
		always: false,
	},
	{
		key: 'startedAt',
		labelKey: 'field-started-at',
		category: 'personal',
		type: 'date',
		personal: true,
		graphql: 'startedAt { year month day }',
		always: false,
	},
	{
		key: 'completedAt',
		labelKey: 'field-completed-at',
		category: 'personal',
		type: 'date',
		personal: true,
		graphql: 'completedAt { year month day }',
		always: false,
	},
	{
		key: 'notes',
		labelKey: 'field-notes',
		category: 'personal',
		type: 'string',
		personal: true,
		graphql: 'notes',
		always: false,
	},
	{
		key: 'repeat',
		labelKey: 'field-repeat',
		category: 'personal',
		type: 'number',
		personal: true,
		graphql: 'repeat',
		always: false,
	},
	{
		key: 'progressVolumes',
		labelKey: 'field-progress-volumes',
		category: 'personal',
		type: 'number',
		personal: true,
		graphql: 'progressVolumes',
		always: false,
	},
];
